// @ts-check
import nextPlugin from "@next/eslint-plugin-next";
import { defineConfig, globalIgnores } from "eslint/config";
import tseslint from "typescript-eslint";

/**
 * ESLint here is deliberately NOT a general linter. Per docs/CODE_QUALITY.md
 * ("The Biome / typescript-eslint split, explained") it runs exactly two things:
 *
 *  1. typescript-eslint's `strictTypeCheckedOnly` family — the rules that need
 *     the TypeScript type checker and that Biome, which has no type
 *     information, structurally cannot implement (`no-floating-promises`,
 *     `no-misused-promises`, `await-thenable`, the unsafe-`any` flow rules).
 *     The `...Only` variants are load-bearing: `strictTypeChecked` would also
 *     pull in the non-type-aware TS rules that Biome already owns, and two
 *     linters with contradictory autofixes is the failure this split exists to
 *     prevent.
 *
 *  2. @next/eslint-plugin-next — the one sanctioned non-type-aware exception
 *     (resolved 2026-07-25). Its rules are Next.js domain rules
 *     (`no-img-element`, `no-html-link-for-pages`), not style, so they cannot
 *     contradict Biome; Biome's own `next` domain is switched off in
 *     biome.jsonc for the same reason. The full `eslint-config-next` preset
 *     stays rejected — it drags in the style/import rules Biome owns.
 *
 * Everything else (formatting, import order, unused imports, a11y, plain
 * correctness) is Biome's. Do not add a rule here that runs without type
 * information unless it is a Next.js domain rule.
 */
export default defineConfig([
  globalIgnores([
    ".next/**",
    "out/**",
    // Generated by `next typegen`; Next's own header says do not edit it.
    "next-env.d.ts",
  ]),

  {
    name: "learntrail/type-aware",
    // Scoped to TypeScript only. The .mjs config files in this package are not
    // in tsconfig's `include`, so a type-aware pass over them would either
    // error out or need `allowDefaultProject` — and there is nothing for
    // type-aware rules to say about them anyway. Biome lints them instead.
    files: ["**/*.ts", "**/*.tsx", "**/*.mts"],
    extends: [tseslint.configs.strictTypeCheckedOnly],
    languageOptions: {
      parserOptions: {
        // projectService is what makes every rule below type-aware: it hands
        // the parser the real TypeScript program from tsconfig.json. Without
        // it, ESLint silently runs zero of these rules.
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // typescript-eslint's type-checked configs also switch on ESLint core's
      // TypeScript-flavoured `eslint:recommended` layer, which enables exactly
      // these four rules. None of them needs the type checker, so all four are
      // Biome's by the split. Their Biome equivalents are guaranteed on in
      // biome.jsonc: useConst, noArguments (recommended preset) plus noVar and
      // useSpreadOverApply (enabled explicitly there). Do not delete one side
      // of this pair without the other.
      "no-var": "off",
      "prefer-const": "off",
      "prefer-rest-params": "off",
      "prefer-spread": "off",
    },
  },

  {
    name: "learntrail/next",
    files: ["**/*.ts", "**/*.tsx"],
    plugins: { "@next/next": nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
    },
  },
]);
