/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chats
         * @description List chats, most recently active first.
         *
         *     Deleted chats are excluded by default — the common case is "show me my
         *     chats", and a soft-deleted one reappearing in that list would make deletion
         *     look broken. `ix_chat_active_recent` is the partial index built for exactly
         *     this query.
         */
        get: operations["list_chats_chats_get"];
        put?: never;
        /**
         * Create Chat
         * @description Create a chat, optionally titled.
         */
        post: operations["create_chat_chats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat
         * @description Resume a conversation: the chat plus its full transcript, in order.
         *
         *     This endpoint *is* the Phase 1 exit criterion. Stop the application, restart
         *     it, call this, and the conversation is still there — because it was never in
         *     memory to begin with.
         */
        get: operations["get_chat_chats__chat_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Chat
         * @description Soft-delete a chat. The row and its messages survive; only the two
         *     lifecycle columns change, so restore is possible (docs/SPEC.md §6).
         *
         *     Idempotent, per HTTP's semantics for DELETE: deleting an
         *     already-deleted chat succeeds and does not move `deleted_at`, so the
         *     original deletion time is not overwritten by a retry.
         */
        delete: operations["delete_chat_chats__chat_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename Chat
         * @description Rename a chat.
         */
        patch: operations["rename_chat_chats__chat_id__patch"];
        trace?: never;
    };
    "/chats/{chat_id}/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Chat Title
         * @description Name an untitled chat from its opening turns (docs/SPEC.md §6).
         *
         *     The missing half of "a chat is created before it has a title". Without this
         *     endpoint nothing ever writes `chat.title` except a manual rename, so every
         *     conversation stays `Untitled` in the sidebar forever.
         *
         *     **Never overwrites an existing title.** A chat that already has one is
         *     returned unchanged, with a 200 — which makes the endpoint safe to call
         *     unconditionally after the first answer, and makes it impossible for a
         *     background retitle to discard a name the user chose by hand. Renaming is
         *     `PATCH /chats/{id}`, and that is the only thing that replaces a title.
         */
        post: operations["generate_chat_title_chats__chat_id__title_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Chat
         * @description Undo a soft delete. Idempotent: restoring an active chat is a no-op.
         */
        post: operations["restore_chat_chats__chat_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Append Message
         * @description Append the user's turn to a chat.
         *
         *     Returns only the persisted user message. The assistant's answer is a
         *     separate endpoint (docs/SPEC.md §6 lists "sending messages" and "streaming
         *     answers" separately) and arrives with the SSE endpoint later in Phase 1.
         *
         *     `role` is fixed to `user` rather than taken from the body: a client may only
         *     append its own turn. Letting it choose would let it forge an assistant
         *     message, and from Phase 3 an approved Learning is derived from this
         *     transcript — so a forged turn would be a route to laundering model output
         *     past the human approval gate (CLAUDE.md invariant #5).
         */
        post: operations["append_message_chats__chat_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Answer
         * @description Stream the assistant's answer to the conversation so far, then persist it.
         *
         *     The answer half of "send a message" — docs/SPEC.md §6 lists streaming answers
         *     as its own endpoint, and this is it. `POST /chats/{id}/messages` appends the
         *     question; this produces the reply.
         *
         *     **Phase 2 replaced the direct model call here with a graph invocation.** What
         *     this handler now does is translate: HTTP in, graph state out, graph events
         *     back to SSE. The five steps of the workflow — validate, build context, choose
         *     model, generate, persist — live in `ai_core.graphs.chat`, where each is a
         *     named node the checkpointer records.
         *
         *     The HTTP-level checks below survive that move on purpose. They are not a
         *     duplicate of the graph's `validate_input`: these exist to produce *status
         *     codes*, and a status code can only be sent before the stream opens. The graph
         *     node guards the graph's own preconditions for any caller, including ones that
         *     never came through HTTP.
         *
         *     Consume it with `fetch` + a ReadableStream, not `EventSource`: EventSource
         *     only issues GET requests, and this endpoint is a POST because it creates a
         *     message.
         */
        post: operations["stream_answer_chats__chat_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pending Draft
         * @description The draft currently awaiting review for a chat.
         */
        get: operations["get_pending_draft_chats__chat_id__summary_get"];
        put?: never;
        /**
         * Generate Summary
         * @description Summarise a conversation into a draft awaiting review.
         *
         *     Runs the summary graph until it interrupts for approval. What comes back is a
         *     *draft* — model output the user has not yet accepted.
         *
         *     Calling this again replaces any pending draft for the chat, which is what
         *     "regenerate" means (docs/SPEC.md §15). A partial unique index enforces the
         *     one-pending-draft rule at the database level, so the replacement is not a
         *     convention this handler could forget.
         *
         *     A summary that fails validation is a 422 and **nothing is written** — that is
         *     the Phase 3 exit criterion, and it holds because the graph raises before
         *     reaching its `store_draft` node.
         */
        post: operations["generate_summary_chats__chat_id__summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summaries/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit Draft
         * @description Edit a draft before approving it.
         *
         *     Edits land on the draft, not on a Learning: nothing here has been approved
         *     yet. The graph run stays interrupted throughout — editing is not a decision,
         *     and a user may edit repeatedly before making one.
         */
        patch: operations["edit_draft_summaries__draft_id__patch"];
        trace?: never;
    };
    "/summaries/{draft_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Draft
         * @description Promote a draft into a Learning. **The only path by which one is created.**
         *
         *     Resumes the interrupted graph with the human's decision, so the promotion
         *     happens inside the workflow that produced the draft rather than beside it.
         *
         *     The approved content is the draft's *current* content, edits included — the
         *     user approves what they are looking at, not what the model first produced.
         *     Revision 1 records `change_source=model` regardless, because the text
         *     originated as a generated draft; a later edit writes `human`.
         */
        post: operations["approve_draft_summaries__draft_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summaries/{draft_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Draft
         * @description Decline a draft. Nothing is promoted; the draft is kept as a record.
         */
        post: operations["reject_draft_summaries__draft_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Learnings
         * @description My Learnings — everything the user has approved, most recent first.
         */
        get: operations["list_learnings_learnings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learnings/{learning_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Learning
         * @description One Learning with its full revision history.
         */
        get: operations["get_learning_learnings__learning_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Learning
         * @description Soft-delete a Learning. Restorable, like a chat (docs/SPEC.md §6).
         */
        delete: operations["delete_learning_learnings__learning_id__delete"];
        options?: never;
        head?: never;
        /**
         * Edit Learning
         * @description Edit an approved Learning, writing a new revision.
         *
         *     The previous content is not overwritten in place — it becomes history. That
         *     is what lets the library answer "what did this say when I approved it", which
         *     is the question that makes an edited Learning trustworthy rather than merely
         *     current.
         */
        patch: operations["edit_learning_learnings__learning_id__patch"];
        trace?: never;
    };
    "/learnings/{learning_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Learning
         * @description Undo a soft delete.
         */
        post: operations["restore_learning_learnings__learning_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learnings/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Learnings
         * @description Hybrid search over approved Learnings. No model call, no generated answer.
         *
         *     POST rather than GET with a query string: the question is user content of
         *     unbounded length, and it belongs in a body rather than in a URL that ends up
         *     in logs and browser history. It is also validated by the same schema the ask
         *     endpoint uses, which keeps the two from disagreeing about what a question is.
         */
        post: operations["search_learnings_learnings_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learnings/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Learnings
         * @description Answer a question from the approved library, citing what supplied the context.
         *
         *     **The citations come from the retrieval step, not from the answer.** The model
         *     is asked to ground its answer in the passages and to say when they do not
         *     contain the answer; it is *not* asked to emit citation markers. Markers would
         *     be a second, unreliable record of something the system already knows for
         *     certain — and one that can be silently wrong in both directions, inventing a
         *     source or omitting a real one.
         *
         *     An empty library returns `grounded: false` and a plain refusal rather than an
         *     answer from the model's own knowledge. That is the whole point: this endpoint
         *     answers *from your Learnings*, and an ungrounded answer dressed up as a
         *     grounded one is exactly the failure Phase 8's criterion exists to prevent.
         */
        post: operations["ask_learnings_learnings_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learnings/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reindex Learnings
         * @description Rebuild the search index for every live approved Learning.
         *
         *     Explicit rather than automatic-only. Approval and editing keep the index in
         *     step on their own, but a re-index is the correct response to a changed
         *     embedding model, a changed chunking rule, or any doubt at all — and it must be
         *     possible to run it without a redeploy. Idempotent by construction: indexing
         *     replaces a Learning's chunks rather than adding to them.
         */
        post: operations["reindex_learnings_learnings_reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learnings/{learning_id}/flashcards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make Flashcards
         * @description Generate revision flashcards from one approved Learning (Phase 12).
         *
         *     Generated on demand and not stored: flashcards are a study aid derived from
         *     knowledge, not knowledge, so they need no approval gate and no table. Ask
         *     again to get a fresh set.
         *
         *     A deleted Learning is refused with a 409, not quietly used — you should not be
         *     handed cards from something you removed from your library.
         */
        post: operations["make_flashcards_learnings__learning_id__flashcards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Model Comparison
         * @description Per-alias usage over a rolling window.
         *
         *     `window_hours` defaults to a week, which is long enough that a lightly-used
         *     library still has rows to compare and short enough that a routing change made
         *     yesterday is not drowned by a month of the old behaviour.
         *
         *     Latency and cost are averaged in the database rather than in Python: the rows
         *     are the authority, and pulling thousands of them across the wire to average
         *     them here would be the dashboard paying for its own decoration.
         */
        get: operations["model_comparison_models_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AskRequest
         * @description A question to answer from the approved library.
         */
        AskRequest: {
            /** Question */
            question: string;
            /**
             * Limit
             * @default 5
             */
            limit: number;
        };
        /**
         * AskResponse
         * @description An answer grounded in approved Learnings, with its sources.
         *
         *     `citations` is never inferred from the answer text. It is the list of chunks
         *     that were placed in the context, which is what "supplied the context" means —
         *     a Learning the model was given and chose not to lean on still supplied
         *     context, and pretending otherwise would require asking the model to introspect
         *     on its own reasoning.
         */
        AskResponse: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Grounded */
            grounded: boolean;
            /** Trace Id */
            trace_id?: string | null;
        };
        /**
         * ChangeSource
         * @description Who caused a revision (docs/SPEC.md §17, `learning_revision.change_source`).
         *
         *     The distinction the whole approval gate exists to preserve: `MODEL` means the
         *     text came from a generated draft the user approved, `HUMAN` means the user
         *     wrote or edited it themselves. Without this column the library would be a pile
         *     of text with no record of what was authored and what was merely accepted.
         * @enum {string}
         */
        ChangeSource: "model" | "human";
        /**
         * ChatCreate
         * @description Body for creating a chat.
         *
         *     The title is optional because a chat exists before it has one — it is
         *     generated from the conversation afterwards (docs/SPEC.md §6).
         */
        ChatCreate: {
            /** Title */
            title?: string | null;
        };
        /**
         * ChatDetail
         * @description A chat with its full transcript — the resume view.
         *
         *     This is what makes the Phase 1 exit criterion observable: stop the
         *     application, restart it, GET this, and the conversation is still there.
         */
        ChatDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            status: components["schemas"]["ChatStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Messages */
            messages: components["schemas"]["MessageRead"][];
        };
        /**
         * ChatRead
         * @description A chat without its messages — the list view.
         *
         *     `deleted_at` is exposed rather than hidden: a soft-deleted chat is restorable
         *     (docs/SPEC.md §6), so a client needs to be able to show it as deleted rather
         *     than have it silently vanish.
         */
        ChatRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            status: components["schemas"]["ChatStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
        };
        /**
         * ChatRename
         * @description Body for renaming a chat. The title is required — this endpoint's whole
         *     purpose is to set one, so an omitted field is a client error, not a clear.
         */
        ChatRename: {
            /** Title */
            title: string;
        };
        /**
         * ChatStatus
         * @description Lifecycle of a chat.
         *
         *     Kept in lockstep with ``Chat.deleted_at`` by a CHECK constraint: a chat is
         *     `deleted` exactly when it carries a deletion timestamp. Two columns for one
         *     fact is redundant, and docs/SPEC.md §17 lists both, so the redundancy is
         *     made unbreakable at the database level instead of trusted to application
         *     code. `status` is what queries filter on; `deleted_at` is when it happened,
         *     which is what makes restore possible.
         * @enum {string}
         */
        ChatStatus: "active" | "deleted";
        /**
         * Citation
         * @description One approved Learning that supplied context, and the passage it supplied.
         *
         *     **This type is Phase 8's exit criterion.** The criterion asks that an answer
         *     identify *exactly* which approved Learning supplied its context, and a
         *     citation built from the retrieval record does that by construction: the
         *     `learning_id` is the row the chunk came from, not a number the model wrote in
         *     its prose and might have invented or omitted.
         *
         *     `excerpt` is the chunk text verbatim, so a reader can check the answer against
         *     what the model was actually given rather than against the Learning as it
         *     stands today — those differ the moment the Learning is edited.
         */
        Citation: {
            /**
             * Learning Id
             * Format: uuid
             */
            learning_id: string;
            /** Learning Title */
            learning_title: string;
            /** Chunk Index */
            chunk_index: number;
            /** Excerpt */
            excerpt: string;
            /** Score */
            score: number;
            /** Matched By */
            matched_by: string;
        };
        /**
         * DraftStatus
         * @description Where a draft is in review (docs/SPEC.md §4).
         *
         *     A draft leaves `PENDING` exactly once. `APPROVED` records that it became a
         *     Learning; `REJECTED` records that the user said no. Both are kept rather than
         *     deleted — "the model proposed this and I declined" is information, and Phase 6
         *     evaluates on precisely that signal.
         * @enum {string}
         */
        DraftStatus: "pending" | "approved" | "rejected";
        /**
         * FlashcardRead
         * @description One generated flashcard.
         */
        FlashcardRead: {
            /** Front */
            front: string;
            /** Back */
            back: string;
        };
        /**
         * FlashcardSetRead
         * @description A generated set for one Learning.
         *
         *     Carries the `learning_id` it was made from, so the client can show the cards
         *     beside their source — the cards are only trustworthy as revision if you can
         *     check them against the Learning they came from.
         */
        FlashcardSetRead: {
            /**
             * Learning Id
             * Format: uuid
             */
            learning_id: string;
            /** Cards */
            cards: components["schemas"]["FlashcardRead"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LearningDetail
         * @description An approved Learning with its full revision history.
         */
        LearningDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Chat Id */
            source_chat_id: string | null;
            /** Title */
            title: string;
            /** Structured Content */
            structured_content: {
                [key: string]: unknown;
            };
            /**
             * Approved At
             * Format: date-time
             */
            approved_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Revisions */
            revisions: components["schemas"]["LearningRevisionRead"][];
        };
        /**
         * LearningEdit
         * @description A human edit to an approved Learning. Writes a new revision.
         */
        LearningEdit: {
            content: components["schemas"]["SummaryContent"];
            /** Note */
            note?: string | null;
        };
        /**
         * LearningRead
         * @description An approved Learning, without its history — the library list view.
         */
        LearningRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Chat Id */
            source_chat_id: string | null;
            /** Title */
            title: string;
            /** Structured Content */
            structured_content: {
                [key: string]: unknown;
            };
            /**
             * Approved At
             * Format: date-time
             */
            approved_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
        };
        /**
         * LearningRevisionRead
         * @description One version of a Learning's content.
         */
        LearningRevisionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revision Number */
            revision_number: number;
            /** Structured Content */
            structured_content: {
                [key: string]: unknown;
            };
            change_source: components["schemas"]["ChangeSource"];
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MessageCreate
         * @description Body for appending a message.
         *
         *     Deliberately does **not** accept `role` or `sequence_number`. A client may
         *     only ever append its own turn, and the position in the transcript is the
         *     server's to assign — accepting either would let a caller forge an assistant
         *     message or reorder history.
         */
        MessageCreate: {
            /** Content */
            content: string;
        };
        /**
         * MessageRead
         * @description One persisted turn.
         */
        MessageRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["MessageRole"];
            /** Content */
            content: string;
            /** Sequence Number */
            sequence_number: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Trace Id */
            trace_id?: string | null;
        };
        /**
         * MessageRole
         * @description Who produced a message.
         *
         *     `system` is stored rather than assembled on the fly so a conversation can be
         *     replayed exactly as it was sent — a prompt change must not retroactively
         *     rewrite what the model actually saw.
         * @enum {string}
         */
        MessageRole: "user" | "assistant" | "system";
        /**
         * ModelComparison
         * @description The dashboard payload: usage per alias, best-used first.
         */
        ModelComparison: {
            /** Window Hours */
            window_hours: number;
            /** Usage */
            usage: components["schemas"]["ModelUsage"][];
        };
        /**
         * ModelUsage
         * @description One alias's usage over the window. Every field comes from `model_run`.
         */
        ModelUsage: {
            /** Model Alias */
            model_alias: string;
            /** Runs */
            runs: number;
            /** Total Cost */
            total_cost: number;
            /** Avg Latency Ms */
            avg_latency_ms: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Blocked */
            blocked: number;
        };
        /**
         * SearchResult
         * @description What a plain search returns: passages, no generated answer.
         */
        SearchResult: {
            /** Query */
            query: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /**
         * SummaryContent
         * @description The editable body of a draft or a Learning.
         *
         *     A separate type from `ai_core.schemas.summary.LearningSummary` on purpose,
         *     even though the fields match. That one is what a *model* must produce and is
         *     validated on the way out of the model; this one is what a *person* may submit
         *     when they edit. Sharing the type would mean either loosening the model's
         *     contract or imposing generation-time rules on a human's edit — and a user who
         *     wants to delete every open question from their own Learning is entitled to.
         */
        SummaryContent: {
            /** Title */
            title: string;
            /** Overview */
            overview: string;
            /** Key Concepts */
            key_concepts?: string[];
            /** Distinctions */
            distinctions?: string[];
            /** Examples */
            examples?: string[];
            /** Open Questions */
            open_questions?: string[];
            /** Suggested Tags */
            suggested_tags?: string[];
            /** Uncertainty Notes */
            uncertainty_notes?: string[];
        };
        /**
         * SummaryDraftRead
         * @description A draft awaiting review. Model output, not knowledge.
         */
        SummaryDraftRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Chat Id
             * Format: uuid
             */
            chat_id: string;
            /** Title */
            title: string;
            /** Structured Content */
            structured_content: {
                [key: string]: unknown;
            };
            status: components["schemas"]["DraftStatus"];
            /** Prompt Version */
            prompt_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_chats_chats_get: {
        parameters: {
            query?: {
                /** @description Include soft-deleted chats in the listing. */
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_chat_chats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_chats__chat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chat_chats__chat_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_chat_chats__chat_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_chat_title_chats__chat_id__title_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_chat_chats__chat_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    append_message_chats__chat_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_answer_chats__chat_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pending_draft_chats__chat_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryDraftRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_summary_chats__chat_id__summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryDraftRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_draft_summaries__draft_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryContent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryDraftRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_draft_summaries__draft_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_draft_summaries__draft_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_learnings_learnings_get: {
        parameters: {
            query?: {
                /** @description Include soft-deleted. */
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_learning_learnings__learning_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                learning_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_learning_learnings__learning_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                learning_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_learning_learnings__learning_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                learning_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_learning_learnings__learning_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                learning_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_learnings_learnings_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_learnings_learnings_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_learnings_learnings_reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    make_flashcards_learnings__learning_id__flashcards_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                learning_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardSetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_comparison_models_comparison_get: {
        parameters: {
            query?: {
                window_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
