/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chats
         * @description List chats, most recently active first.
         *
         *     Deleted chats are excluded by default — the common case is "show me my
         *     chats", and a soft-deleted one reappearing in that list would make deletion
         *     look broken. `ix_chat_active_recent` is the partial index built for exactly
         *     this query.
         */
        get: operations["list_chats_chats_get"];
        put?: never;
        /**
         * Create Chat
         * @description Create a chat, optionally titled.
         */
        post: operations["create_chat_chats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat
         * @description Resume a conversation: the chat plus its full transcript, in order.
         *
         *     This endpoint *is* the Phase 1 exit criterion. Stop the application, restart
         *     it, call this, and the conversation is still there — because it was never in
         *     memory to begin with.
         */
        get: operations["get_chat_chats__chat_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Chat
         * @description Soft-delete a chat. The row and its messages survive; only the two
         *     lifecycle columns change, so restore is possible (docs/SPEC.md §6).
         *
         *     Idempotent, per HTTP's semantics for DELETE: deleting an
         *     already-deleted chat succeeds and does not move `deleted_at`, so the
         *     original deletion time is not overwritten by a retry.
         */
        delete: operations["delete_chat_chats__chat_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename Chat
         * @description Rename a chat.
         */
        patch: operations["rename_chat_chats__chat_id__patch"];
        trace?: never;
    };
    "/chats/{chat_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Chat
         * @description Undo a soft delete. Idempotent: restoring an active chat is a no-op.
         */
        post: operations["restore_chat_chats__chat_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Append Message
         * @description Append the user's turn to a chat.
         *
         *     Returns only the persisted user message. The assistant's answer is a
         *     separate endpoint (docs/SPEC.md §6 lists "sending messages" and "streaming
         *     answers" separately) and arrives with the SSE endpoint later in Phase 1.
         *
         *     `role` is fixed to `user` rather than taken from the body: a client may only
         *     append its own turn. Letting it choose would let it forge an assistant
         *     message, and from Phase 3 an approved Learning is derived from this
         *     transcript — so a forged turn would be a route to laundering model output
         *     past the human approval gate (CLAUDE.md invariant #5).
         */
        post: operations["append_message_chats__chat_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Answer
         * @description Stream the assistant's answer to the conversation so far, then persist it.
         *
         *     The answer half of "send a message" — docs/SPEC.md §6 lists streaming answers
         *     as its own endpoint, and this is it. `POST /chats/{id}/messages` appends the
         *     question; this produces the reply.
         *
         *     Validation happens *before* the response begins. Once a stream is open the
         *     status line is already sent, so a 404 or 409 is no longer expressible — the
         *     error would have to arrive as an SSE `error` event that a client is free to
         *     ignore. Everything that can be checked up front therefore is.
         *
         *     Consume it with `fetch` + a ReadableStream, not `EventSource`: EventSource
         *     only issues GET requests, and this endpoint is a POST because it creates a
         *     message.
         */
        post: operations["stream_answer_chats__chat_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatCreate
         * @description Body for creating a chat.
         *
         *     The title is optional because a chat exists before it has one — it is
         *     generated from the conversation afterwards (docs/SPEC.md §6).
         */
        ChatCreate: {
            /** Title */
            title?: string | null;
        };
        /**
         * ChatDetail
         * @description A chat with its full transcript — the resume view.
         *
         *     This is what makes the Phase 1 exit criterion observable: stop the
         *     application, restart it, GET this, and the conversation is still there.
         */
        ChatDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            status: components["schemas"]["ChatStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Messages */
            messages: components["schemas"]["MessageRead"][];
        };
        /**
         * ChatRead
         * @description A chat without its messages — the list view.
         *
         *     `deleted_at` is exposed rather than hidden: a soft-deleted chat is restorable
         *     (docs/SPEC.md §6), so a client needs to be able to show it as deleted rather
         *     than have it silently vanish.
         */
        ChatRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            status: components["schemas"]["ChatStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
        };
        /**
         * ChatRename
         * @description Body for renaming a chat. The title is required — this endpoint's whole
         *     purpose is to set one, so an omitted field is a client error, not a clear.
         */
        ChatRename: {
            /** Title */
            title: string;
        };
        /**
         * ChatStatus
         * @description Lifecycle of a chat.
         *
         *     Kept in lockstep with ``Chat.deleted_at`` by a CHECK constraint: a chat is
         *     `deleted` exactly when it carries a deletion timestamp. Two columns for one
         *     fact is redundant, and docs/SPEC.md §17 lists both, so the redundancy is
         *     made unbreakable at the database level instead of trusted to application
         *     code. `status` is what queries filter on; `deleted_at` is when it happened,
         *     which is what makes restore possible.
         * @enum {string}
         */
        ChatStatus: "active" | "deleted";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MessageCreate
         * @description Body for appending a message.
         *
         *     Deliberately does **not** accept `role` or `sequence_number`. A client may
         *     only ever append its own turn, and the position in the transcript is the
         *     server's to assign — accepting either would let a caller forge an assistant
         *     message or reorder history.
         */
        MessageCreate: {
            /** Content */
            content: string;
        };
        /**
         * MessageRead
         * @description One persisted turn.
         */
        MessageRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["MessageRole"];
            /** Content */
            content: string;
            /** Sequence Number */
            sequence_number: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MessageRole
         * @description Who produced a message.
         *
         *     `system` is stored rather than assembled on the fly so a conversation can be
         *     replayed exactly as it was sent — a prompt change must not retroactively
         *     rewrite what the model actually saw.
         * @enum {string}
         */
        MessageRole: "user" | "assistant" | "system";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_chats_chats_get: {
        parameters: {
            query?: {
                /** @description Include soft-deleted chats in the listing. */
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_chat_chats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_chats__chat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chat_chats__chat_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_chat_chats__chat_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_chat_chats__chat_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    append_message_chats__chat_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_answer_chats__chat_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
