"""The single declarative base every LearnTrail table will hang off.

Phase 0 deliberately leaves this base **empty**: `Base.metadata` has zero
tables, so `alembic revision --autogenerate` would emit an empty migration.
That is the intended end state of this task — a runnable migration env with
nothing to migrate yet. Phase 1 adds `chat` and `message` (docs/SPEC.md §17).

There is no `user` model here and never will be: LearnTrail is single-user with
no auth (CLAUDE.md invariant #1).
"""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Deterministic, explicit names for every generated constraint and index.
# Set *before* the first migration on purpose: without it, Postgres invents
# names for unnamed constraints, autogenerated downgrades cannot reliably drop
# them, and `alembic revision --autogenerate` produces unstable diffs. Changing
# this later would mean renaming live constraints, so it belongs in the empty
# base, not in the first table's migration.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for all LearnTrail ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
