"""add pgvector and learning_chunk

The vector extension, the chunk table, and the two indexes that make hybrid
search possible (docs/SPEC.md §17, Phase 8).

Written by hand rather than autogenerated. Alembic's autogenerate does not emit
`CREATE EXTENSION`, and it cannot express either index here: the HNSW index needs
an operator class and build parameters, and the full-text index is over an
expression rather than a column. An autogenerated skeleton would have produced a
table that works and a search that falls back to a sequential scan — which is
correct and slow, and therefore the kind of bug nobody notices until the library
is large.

Revision ID: efa5b20904df
Revises: 21fa67457e0f
Create Date: 2026-07-28 21:03:35.709615+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

revision: str = "efa5b20904df"
down_revision: str | None = "21fa67457e0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Matches `database.models.knowledge.EMBEDDING_DIMENSIONS`. Restated rather than
#: imported: a migration must keep describing the schema it created even after the
#: application's constant moves on, or replaying history stops reproducing it.
EMBEDDING_DIMENSIONS = 1536


def upgrade() -> None:
    """Apply this revision."""
    # The extension is a property of the database, not of a table, and it must
    # exist before the column type below can be resolved. `IF NOT EXISTS` because
    # a database restored from a dump may already have it.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "learning_chunk",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("learning_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(EMBEDDING_DIMENSIONS), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "chunk_index >= 0", name=op.f("ck_learning_chunk_chunk_index_non_negative")
        ),
        sa.CheckConstraint(
            "length(trim(content)) > 0", name=op.f("ck_learning_chunk_content_not_blank")
        ),
        # CASCADE: a chunk is a projection of its Learning. One that outlived its
        # source would be citable context pointing at nothing.
        sa.ForeignKeyConstraint(
            ["learning_id"],
            ["learning.id"],
            name=op.f("fk_learning_chunk_learning_id_learning"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_chunk")),
        sa.UniqueConstraint(
            "learning_id", "chunk_index", name=op.f("uq_learning_chunk_learning_id_chunk_index")
        ),
    )
    op.create_index("ix_learning_chunk_learning", "learning_chunk", ["learning_id"])

    # --- semantic half of hybrid search ---------------------------------------
    # HNSW rather than IVFFlat. IVFFlat needs to be built *after* the table holds
    # a representative sample — it clusters existing rows — so building one on an
    # empty table produces an index that degrades as the library grows and has to
    # be rebuilt to recover. HNSW builds incrementally and is correct from the
    # first row, which matters here because the library starts empty and fills up
    # one approval at a time.
    #
    # `vector_cosine_ops` because the search normalises on direction, not
    # magnitude: two passages about the same idea should match even when one is
    # three times longer. The query side must use the matching `<=>` operator or
    # the index is silently skipped.
    op.execute(
        "CREATE INDEX ix_learning_chunk_embedding_hnsw "
        "ON learning_chunk USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )

    # --- lexical half ---------------------------------------------------------
    # An expression index over `to_tsvector`, not a stored tsvector column. The
    # column would be the faster choice at scale and is the usual advice; here it
    # would add a generated column that Alembic's autogenerate cannot round-trip,
    # for a table that will hold thousands of rows rather than millions.
    #
    # `english` is a real choice with a real cost: it stems, so "indexing" matches
    # "index", and it will do the wrong thing for a Learning written in another
    # language. Single-user product, one known user, one language.
    op.execute(
        "CREATE INDEX ix_learning_chunk_content_fts "
        "ON learning_chunk USING gin (to_tsvector('english', content))"
    )


def downgrade() -> None:
    """Revert this revision."""
    op.execute("DROP INDEX IF EXISTS ix_learning_chunk_content_fts")
    op.execute("DROP INDEX IF EXISTS ix_learning_chunk_embedding_hnsw")
    op.drop_index("ix_learning_chunk_learning", table_name="learning_chunk")
    op.drop_table("learning_chunk")
    # The extension is deliberately NOT dropped. Another table may come to depend
    # on it, and dropping an extension takes every dependent object with it — a
    # downgrade that silently deletes unrelated data is worse than one that leaves
    # a harmless extension installed.
