"""add chat and message

The first revision in the repo: the conversation aggregate from docs/SPEC.md §17.
Autogenerated from database.models.conversation and then read line by line —
every constraint name below comes from the naming convention set on `Base` in
Phase 0, which is why they are all explicit rather than left to Postgres.

There is no `user` table and no `user_id` column, here or in any later revision
(CLAUDE.md invariant #1).

Revision ID: 6ab72a617d4e
Revises:
Create Date: 2026-07-26 14:25:40.843807+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6ab72a617d4e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "chat",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'deleted') = (deleted_at IS NOT NULL)",
            name=op.f("ck_chat_status_matches_deleted_at"),
        ),
        sa.CheckConstraint("status IN ('active', 'deleted')", name=op.f("ck_chat_status_is_known")),
        sa.CheckConstraint(
            "title IS NULL OR length(trim(title)) > 0", name=op.f("ck_chat_title_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat")),
    )
    op.create_index(
        "ix_chat_active_recent",
        "chat",
        ["updated_at"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('user', 'assistant', 'system')", name=op.f("ck_message_role_is_known")
        ),
        sa.CheckConstraint("length(content) > 0", name=op.f("ck_message_content_not_empty")),
        sa.CheckConstraint(
            "sequence_number >= 0", name=op.f("ck_message_sequence_number_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chat.id"], name=op.f("fk_message_chat_id_chat"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message")),
        sa.UniqueConstraint(
            "chat_id", "sequence_number", name=op.f("uq_message_chat_id_sequence_number")
        ),
    )


def downgrade() -> None:
    """Revert this revision."""
    op.drop_table("message")
    op.drop_index(
        "ix_chat_active_recent", table_name="chat", postgresql_where=sa.text("status = 'active'")
    )
    op.drop_table("chat")
