"""Metadata-level contract for the persistence layer.

No database is required to run any of this: nothing here creates an engine,
opens a connection or reflects anything. These are the properties that can be
checked from metadata alone — which tables are registered, the naming convention
fixed before the first migration, and a URL that comes from the environment.
Behaviour that needs a live Postgres (the CHECK constraints actually rejecting
bad rows) lives in test_conversation.py.
"""

import pytest

from database.base import Base
from database.config import DEFAULT_DATABASE_URL, database_url

# The tables registered so far: the conversation aggregate (Phase 1) and the
# knowledge aggregate (Phase 3). The remaining docs/SPEC.md §17 tables arrive with
# the phase that introduces their concept, so this is an exact comparison — a
# table appearing early is a phase violation (CLAUDE.md invariant #6), not a head
# start, and adding one is meant to fail this test.
#
# LangGraph's checkpoint tables are deliberately absent: the library owns them,
# they are created by its `setup()`, and `migrations/env.py` filters autogenerate
# down to the tables in this metadata precisely so Alembic never proposes
# dropping them.
EXPECTED_TABLES = frozenset(
    {
        "chat",
        "message",
        "summary_draft",
        "learning",
        "learning_revision",
        "safety_event",
        "model_run",
        "evaluation_case",
        "evaluation_result",
        "learning_chunk",
    }
)


def test_metadata_declares_exactly_the_expected_tables() -> None:
    # Populated by importing `database.models`, which `database/__init__.py` does
    # on package import — the same mechanism migrations/env.py relies on. If that
    # import is ever dropped, this fails rather than autogenerate silently
    # emitting a migration that drops every table.
    assert set(Base.metadata.tables) == set(EXPECTED_TABLES)


def test_metadata_never_models_a_user() -> None:
    """CLAUDE.md invariant #1, as an assertion rather than a promise.

    Unlike every other test in this file, this one is **phase-independent**: it
    is vacuously true today and must still pass in Phase 12. It is deliberately
    written against whatever `Base.metadata` happens to contain, so it starts
    guarding the invariant the moment Phase 1 adds the first real table. Do not
    rewrite it into a Phase-0-shaped assertion.
    """
    table_names = set(Base.metadata.tables)
    assert "user" not in table_names
    assert "users" not in table_names

    offenders = {
        f"{table.name}.{column.name}"
        for table in Base.metadata.tables.values()
        for column in table.columns
        if column.name == "user_id"
    }
    assert offenders == set(), f"no user_id column may ever exist; found {sorted(offenders)}"


def test_metadata_has_a_full_naming_convention() -> None:
    # Must be in place *before* the first migration: without it Postgres invents
    # names for unnamed constraints and autogenerated downgrades cannot drop
    # them. Keys are spelled out rather than imported from `database.base`, so
    # this fails if one is dropped instead of agreeing with itself.
    assert set(Base.metadata.naming_convention) == {"ix", "uq", "ck", "fk", "pk"}
    assert Base.metadata.naming_convention["pk"] == "pk_%(table_name)s"


def test_database_url_prefers_the_environment(monkeypatch: pytest.MonkeyPatch) -> None:
    # The env var name is the contract docker-compose will hand the backend
    # (plans/phase-0.md task 8), so it is asserted as a literal.
    monkeypatch.setenv("DATABASE_URL", "postgresql+psycopg://someone@db.internal:5432/other")
    assert database_url() == "postgresql+psycopg://someone@db.internal:5432/other"


def test_database_url_falls_back_when_unset_or_empty(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("DATABASE_URL", raising=False)
    assert database_url() == DEFAULT_DATABASE_URL
    # An empty value is a misconfigured environment, not an instruction to
    # connect to "" — `database_url()` treats it as unset.
    monkeypatch.setenv("DATABASE_URL", "")
    assert database_url() == DEFAULT_DATABASE_URL


def test_default_url_pins_the_psycopg3_dialect() -> None:
    # Load-bearing: a bare `postgresql://` URL resolves to psycopg2, which is
    # deliberately not a dependency and fails at import.
    assert DEFAULT_DATABASE_URL.startswith("postgresql+psycopg://")
